### ISSUE TITLE
Bot service stopped responding to queries

### ISSUE THREAD

**Issue by gushcha** [gushcha/unforgivingbot#4]
Dispute key duplication causes transaction stop and bot service is stuck
```
2023-05-09 06:59:09,026 - unforgivingbot - ERROR - duplicate key value violates unique constraint "disputes_pkey"
DETAIL:  Key (id)=(Lmxy) already exists.
Traceback (most recent call last):
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 98, in _process_task
    await self._submit_and_subscribe(inline_message_id, dispute_query_user_id, from_user)
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 46, in _submit_and_subscribe
    await dispute_create(dispute)
  File "/home/ubuntu/unforgivingbot/dao/disputes_dao.py", line 13, in create
    await cursor.execute('''insert into disputes \
  File "/home/ubuntu/unforgivingbot/venv/lib/python3.11/site-packages/psycopg/cursor_async.py", line 94, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "disputes_pkey"
DETAIL:  Key (id)=(Lmxy) already exists.
2023-05-09 06:59:09,031 - unforgivingbot - ERROR - current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 98, in _process_task
    await self._submit_and_subscribe(inline_message_id, dispute_query_user_id, from_user)
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 46, in _submit_and_subscribe
    await dispute_create(dispute)
  File "/home/ubuntu/unforgivingbot/dao/disputes_dao.py", line 13, in create
    await cursor.execute('''insert into disputes \
  File "/home/ubuntu/unforgivingbot/venv/lib/python3.11/site-packages/psycopg/cursor_async.py", line 94, in execute
    raise ex.with_traceback(None)
psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
2023-05-09 06:59:09,033 - unforgivingbot - ERROR - insert or update on table "trackers" violates foreign key constraint "trackers_dispute_id_fkey"
DETAIL:  Key (dispute_id)=(Lmxy) is not present in table "disputes".
Traceback (most recent call last):
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 98, in _process_task
    await self._submit_and_subscribe(inline_message_id, dispute_query_user_id, from_user)
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 48, in _submit_and_subscribe
    await tracker_create(tracker)
  File "/home/ubuntu/unforgivingbot/dao/trackers_dao.py", line 12, in create
    await cursor.execute('''insert into trackers \
  File "/home/ubuntu/unforgivingbot/venv/lib/python3.11/site-packages/psycopg/cursor_async.py", line 94, in execute
    raise ex.with_traceback(None)
psycopg.errors.ForeignKeyViolation: insert or update on table "trackers" violates foreign key constraint "trackers_dispute_id_fkey"
DETAIL:  Key (dispute_id)=(Lmxy) is not present in table "disputes".
2023-05-09 06:59:12,267 - unforgivingbot - DEBUG - Update from tg received: {"update_id": 452877305, "callback_query": {"id": "1288052452408237714", "from": {"id": 299898081, "is_bot": false, "first_name": "zhenasbezhala", "username": "zhenasbezhala", "language_code": "ru"}, "inline_message_id": "AgAAAMIaAwA8bLcJrGWmJfsLKCI", "chat_instance": "673556156836973872", "data": "s Lmxy"}}
2023-05-09 06:59:12,268 - unforgivingbot - ERROR - current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/home/ubuntu/unforgivingbot/processors/processor_callback_query.py", line 100, in _process_task
    dispute = await dispute_read(dispute_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/unforgivingbot/dao/disputes_dao.py", line 27, in read
    await cursor.execute('''select id, text, created_on, ends_on \
  File "/home/ubuntu/unforgivingbot/venv/lib/python3.11/site-packages/psycopg/cursor_async.py", line 94, in execute
    raise ex.with_traceback(None)
psycopg.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

The issue contains 2 bugs:
- Transaction error causes service stuck, but should just print an error
- Duplicates happening

**Comment by gushcha** [comment]
Duplicates not happening, because queries are not cached by tg. Auto commit disabled for submitter.
